import React, { useState } from 'react';
import './DocumentManagement.css';

const DocumentManagement = () => {
  const [documents, setDocuments] = useState([
    { id: 1, name: 'Project Plan', version: '1.0', date: '2023-06-25' },
    { id: 2, name: 'Contract Agreement', version: '2.2', date: '2023-06-28' },
    { id: 3, name: 'Design Specifications', version: '1.5', date: '2023-07-05' },
  ]);

  const updateDocumentVersion = (documentId, newVersion) => {//updates the version of a specific document uses map function to create a new array of the updated documents
    const updatedDocuments = documents.map((document) => {//higher-order function that makes a callback function as an argument and applies it to each element
      if (document.id === documentId) {
        return { ...document, version: newVersion };
      }
      return document;
    });
    setDocuments(updatedDocuments);
  };

  return (
    <div className="document-management">
      <h2>Document Management</h2>
      <table className="document-table">
        <thead>
          <tr>
            <th>Document</th>
            <th>Version</th>
            <th>Date</th>
            <th>Update Version</th>
          </tr>
        </thead>
        <tbody>  {/*jsx elements generated by `documents.map()`are rendered*/}
          {documents.map((document) => (//the code dynamically generates table rows based on the data in the array
            <tr key={document.id}>
              <td>{document.name}</td>
              <td>{document.version}</td>
              <td>{document.date}</td>
              <td>
                <button
                  className="update-button"
                  onClick={() => updateDocumentVersion(document.id, '3.0')}
                >
                  Update
                </button>
              </td>
            </tr>
          ))}
        </tbody>
      </table>
      {/* Version control and document sharing capabilities */}
      <div className="version-control">
        <h3>Version Control &amp; Document Sharing</h3>
        <p>Integrate your version control and document sharing component here.</p>
      </div>
    </div>
  );
};

export default DocumentManagement;
